package gestao.view.formulario;

import gestao.modelo.controller.AutenticacaoController;
//import gestao.modelo.dao.UsuarioDao;
//import gestao.modelo.entidades.Usuario;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
//import java.sql.SQLException;
///import javax.swing.JOptionPane;
//import java.sql.ResultSet;

public class LoginForm extends javax.swing.JFrame {

    private final AutenticacaoController autenticacaoController;
    private JLabel labelLoginMensagem;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents(); // Chama o método para inicializar os componentes visuais
        setLocationRelativeTo(null);
        autenticacaoController = new AutenticacaoController(this);
        eventos();
        txtLoginUsername.setBackground(new java.awt.Color(0,0,0,1));
        txtLoginSenha.setBackground(new java.awt.Color(0,0,0,1));
    }

    private void eventos() {
        botaoLoginLogin.addActionListener(autenticacaoController);
        botaoLoginCancelar.addActionListener(autenticacaoController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        botaoLoginCancelar = new javax.swing.JButton();
        botaoLoginLogin = new javax.swing.JButton();
        txtLoginSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 520));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(850, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 520));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 58, 29));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 190, 102, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 58, 29));
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 270, 110, 40);

        txtLoginUsername.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLoginUsername.setBorder(null);
        txtLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginUsername);
        txtLoginUsername.setBounds(450, 180, 250, 50);

        botaoLoginCancelar.setBackground(new java.awt.Color(253, 214, 214));
        botaoLoginCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botaoLoginCancelar.setForeground(new java.awt.Color(118, 58, 29));
        botaoLoginCancelar.setText("Cancelar");
        botaoLoginCancelar.setBorder(null);
        botaoLoginCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLoginCancelar);
        botaoLoginCancelar.setBounds(610, 370, 141, 46);

        botaoLoginLogin.setBackground(new java.awt.Color(253, 214, 214));
        botaoLoginLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botaoLoginLogin.setForeground(new java.awt.Color(118, 58, 29));
        botaoLoginLogin.setText("Login");
        botaoLoginLogin.setBorder(null);
        botaoLoginLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginLoginActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLoginLogin);
        botaoLoginLogin.setBounds(380, 370, 144, 46);

        txtLoginSenha.setBorder(null);
        txtLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginSenha);
        txtLoginSenha.setBounds(450, 260, 250, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 58, 29));
        jLabel3.setText("LOGIN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 80, 143, 70);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 58, 29));
        jLabel4.setText("GESTÃO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 40, 181, 63);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 58, 29));
        jLabel5.setText("ESTÉTICA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 90, 141, 45);

        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestao/view/imagens/Frame 1.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-10, -20, 1310, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLoginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginLoginActionPerformed

    }//GEN-LAST:event_botaoLoginLoginActionPerformed

    private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsernameActionPerformed

    private void txtLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginSenhaActionPerformed

    private void botaoLoginCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLoginCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLoginCancelar;
    private javax.swing.JButton botaoLoginLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtLoginSenha;
    private javax.swing.JTextField txtLoginUsername;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtLoginUsername() {
        return txtLoginUsername;
    }

    public JTextField getTxtLoginSenha() {
        return txtLoginSenha;
    }

    public JButton getBotaoLoginLogin() {
        return botaoLoginLogin;
    }

    public JButton getBotaoLoginCancelar() {
        return botaoLoginCancelar;
    }

    public JLabel getLabelLoginMensagem() {
        if (labelLoginMensagem == null) {
            // Se labelLoginMensagem for nulo, inicialize-o aqui
            labelLoginMensagem = new JLabel();
        }
        return labelLoginMensagem;
    }
}
